# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
  branches:
    exclude:
    - '*'

stages:
- stage: PullByRequest
  jobs:
    - job: PullRequestNotification
      pool:
        name: SAPDevOps
      steps:       
      - task: CmdLine@2
        inputs:
         script: 'echo Master branch got committed.'
         workingDirectory: './DevOpsAddOnProgram/'

      - task: PowerShell@2
        inputs:
         targetType: 'inline'
         workingDirectory: './DevOpsAddOnProgram/'
         script: |
           Write-Host "##vso[artifact.upload containerfolder=executable;artifactname=exe;]SAPDevOpsUtil.exe"
           
