# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  jobs:
    - job: Build
      pool:
        name: SAPDevOps
      steps:       
      - task: CmdLine@2 
        name: CodeAnalysis
        env:     
         InputJSON: $(testJSON)
         FilePath: $(tempDirectory)  
        inputs:  
         script:                                
            'test.exe'    
         workingDirectory: '.\DevOpsAddOnPrograms\'

      